version: '3'

networks:
  honeypot:

services:
  api:
    build: ./service/
    container_name: api
    ports:
      - "5000"
    environment:
      - FLASK_APP=honeypot
      - FLASK_ENV=development
      - INTERVAL=5
      - MESSAGE=Not Found
    networks:
      - honeypot

  nginx:
    build: ./nginx/
    ports:
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - honeypot
